/**
 * Attendance fraud-path tests.
 *
 * Every test here asserts that a fraudulent check-in attempt FAILS.
 * The new secure model: junior shows personal QR → HOST scans and marks attendance.
 * Junior cannot self-mark; tokens are HMAC-signed, expiring, and single-use.
 */
import { beforeAll, afterAll, describe, it, expect } from 'vitest'
import { createClient, SupabaseClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'
import { resolve } from 'path'

dotenv.config({ path: resolve(process.cwd(), '.env.local') })

const URL  = process.env.NEXT_PUBLIC_SUPABASE_URL!
const ANON = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
const SVC  = process.env.SUPABASE_SERVICE_ROLE_KEY!

const HOST_EMAIL     = 'fraud-host@prepmax-test.local'
const JUDGE_EMAIL    = 'fraud-judge@prepmax-test.local'
const JUNIOR1_EMAIL  = 'fraud-junior1@prepmax-test.local'
const JUNIOR2_EMAIL  = 'fraud-junior2@prepmax-test.local'
const JUNIOR3_EMAIL  = 'fraud-junior3@prepmax-test.local'
const OUTSIDER_EMAIL = 'fraud-outsider@prepmax-test.local'
const PASSWORD       = 'fraud-test-pass-2026!'

let adminSb:        SupabaseClient
let hostClient:     SupabaseClient
let judgeClient:    SupabaseClient
let junior1Client:  SupabaseClient
let junior2Client:  SupabaseClient
let junior3Client:  SupabaseClient
let outsiderClient: SupabaseClient

let hostId:    string
let judgeId:   string
let junior1Id: string
let junior2Id: string
let junior3Id: string
let roomId:    string
let slotId:    string
let slot2Id:   string  // separate slot for mark_attended_direct tests (fresh confirmed seats)

// token generated by junior1 for use across tests
let junior1Token: string

async function makeUser(email: string, canHost = false): Promise<string> {
  const { data: existing } = await adminSb.auth.admin.listUsers({ perPage: 1000 })
  const found = existing?.users?.find((u) => u.email === email)
  if (found) {
    await adminSb.auth.admin.updateUserById(found.id, { password: PASSWORD })
    return found.id
  }
  const { data } = await adminSb.auth.admin.createUser({
    email, password: PASSWORD, email_confirm: true,
  })
  const uid = data.user!.id
  await adminSb.from('profiles').upsert({
    id: uid, email, name: email.split('@')[0],
    year: canHost ? 'second' : 'first',
    can_host_gd: canHost, can_host_pi: canHost,
    is_crisp: false, is_sac: false,
  }, { onConflict: 'id' })
  return uid
}

async function loginClient(email: string): Promise<SupabaseClient> {
  const c = createClient(URL, ANON, { auth: { autoRefreshToken: false, persistSession: false } })
  await c.auth.signInWithPassword({ email, password: PASSWORD })
  return c
}

beforeAll(async () => {
  if (!SVC) throw new Error('SUPABASE_SERVICE_ROLE_KEY not set')
  adminSb = createClient(URL, SVC, { auth: { autoRefreshToken: false, persistSession: false } })

  hostId    = await makeUser(HOST_EMAIL, true)
  judgeId   = await makeUser(JUDGE_EMAIL, true)
  junior1Id = await makeUser(JUNIOR1_EMAIL, false)
  junior2Id = await makeUser(JUNIOR2_EMAIL, false)
  junior3Id = await makeUser(JUNIOR3_EMAIL, false)
  await makeUser(OUTSIDER_EMAIL, false)

  hostClient     = await loginClient(HOST_EMAIL)
  judgeClient    = await loginClient(JUDGE_EMAIL)
  junior1Client  = await loginClient(JUNIOR1_EMAIL)
  junior2Client  = await loginClient(JUNIOR2_EMAIL)
  junior3Client  = await loginClient(JUNIOR3_EMAIL)
  outsiderClient = await loginClient(OUTSIDER_EMAIL)

  const { data: room, error: roomErr } = await adminSb.from('rooms').insert({
    name: 'Fraud Test Room', location: 'Test Block', capacity: 20, is_live: true,
  }).select('id').single()
  if (roomErr || !room) throw new Error(`Room insert failed: ${JSON.stringify(roomErr)}`)
  roomId = room.id

  const start = new Date(Date.now() + 60_000)
  const end   = new Date(Date.now() + 3_660_000)

  // slotId: for mark_attended_by_token tests (junior1 + junior2 enroll here)
  const { data: slot } = await adminSb.from('slots').insert({
    type: 'GD', host_id: hostId, room_id: roomId,
    topic: 'Fraud Test GD', capacity: 4, expert_areas: [],
    start_at: start.toISOString(), end_at: end.toISOString(),
  }).select('id').single()
  slotId = slot!.id
  await adminSb.from('slot_judges').insert({ slot_id: slotId, judge_id: judgeId })
  await junior1Client.rpc('join_slot', { p_slot_id: slotId, p_user_id: junior1Id })
  await junior2Client.rpc('join_slot', { p_slot_id: slotId, p_user_id: junior2Id })
  await hostClient.rpc('start_slot', { p_slot_id: slotId })

  // slot2Id: for mark_attended_direct tests (junior3 enrolls here — fresh confirmed seat)
  const { data: slot2 } = await adminSb.from('slots').insert({
    type: 'GD', host_id: hostId, room_id: roomId,
    topic: 'Direct Mark Test', capacity: 4, expert_areas: [],
    start_at: start.toISOString(), end_at: end.toISOString(),
  }).select('id').single()
  slot2Id = slot2!.id
  await junior3Client.rpc('join_slot', { p_slot_id: slot2Id, p_user_id: junior3Id })
  await hostClient.rpc('start_slot', { p_slot_id: slot2Id })
}, 90_000)

afterAll(async () => {
  await adminSb.from('slots').delete().eq('id', slotId)
  await adminSb.from('slots').delete().eq('id', slot2Id)
  await adminSb.from('rooms').delete().eq('id', roomId)
  const allEmails = [HOST_EMAIL, JUDGE_EMAIL, JUNIOR1_EMAIL, JUNIOR2_EMAIL, JUNIOR3_EMAIL, OUTSIDER_EMAIL]
  const { data: list } = await adminSb.auth.admin.listUsers({ perPage: 1000 })
  for (const email of allEmails) {
    const u = list?.users?.find((x) => x.email === email)
    if (u) await adminSb.auth.admin.deleteUser(u.id)
  }
})

// ─────────────────────────────────────────────────────────────────────────────
describe('old check_in is permanently disabled', () => {
  it('junior calling check_in returns self_checkin_disabled', async () => {
    const { data, error } = await junior1Client.rpc('check_in', {
      p_slot_id: slotId,
      p_token:   'ANYTHING',
    })
    expect(error).toBeNull()
    expect(data.error).toBe('self_checkin_disabled')
  })

  it('host calling check_in also returns self_checkin_disabled', async () => {
    const { data } = await hostClient.rpc('check_in', {
      p_slot_id: slotId,
      p_token:   'ANYTHING',
    })
    expect(data.error).toBe('self_checkin_disabled')
  })
})

// ─────────────────────────────────────────────────────────────────────────────
describe('generate_checkin_token', () => {
  it('confirmed junior can generate a token for a live slot', async () => {
    const { data, error } = await junior1Client.rpc('generate_checkin_token', {
      p_slot_id: slotId,
    })
    expect(error).toBeNull()
    expect(data.error).toBeUndefined()
    expect(typeof data.token).toBe('string')
    // token = user_id:slot_id:exp:hmac — colon-separated 4 parts
    const parts = data.token.split(':')
    expect(parts).toHaveLength(4)
    expect(parts[0]).toBe(junior1Id)   // user_id is in the payload (not hidden)
    expect(parts[1]).toBe(slotId)
    expect(Number(parts[2])).toBeGreaterThan(Date.now() / 1000)
    junior1Token = data.token          // save for later fraud tests
  })

  it('unenrolled user cannot generate a token', async () => {
    const { data } = await outsiderClient.rpc('generate_checkin_token', {
      p_slot_id: slotId,
    })
    // 'not_enrolled' if authenticated but not enrolled; 'unauthorized' if session expired
    // Either way the user cannot get a token — both are correct rejections
    expect(['not_enrolled', 'unauthorized']).toContain(data.error)
  })

  it('token for a non-existent slot returns slot_not_found', async () => {
    const { data } = await junior1Client.rpc('generate_checkin_token', {
      p_slot_id: '00000000-0000-0000-0000-000000000000',
    })
    expect(data.error).toBe('slot_not_found')
  })
})

// ─────────────────────────────────────────────────────────────────────────────
describe('mark_attended_by_token — fraud paths', () => {
  it('FRAUD: junior cannot call mark_attended_by_token (unauthorized)', async () => {
    const { data } = await junior1Client.rpc('mark_attended_by_token', {
      p_slot_id: slotId,
      p_token:   junior1Token,
    })
    // junior1 is not the host/judge — must be rejected
    expect(data.error).toBe('unauthorized')
  })

  it('FRAUD: outsider cannot call mark_attended_by_token (unauthorized)', async () => {
    const { data } = await outsiderClient.rpc('mark_attended_by_token', {
      p_slot_id: slotId,
      p_token:   junior1Token,
    })
    expect(data.error).toBe('unauthorized')
  })

  it('FRAUD: forged token (tampered HMAC) is rejected', async () => {
    const parts = junior1Token.split(':')
    const forgedToken = parts[0] + ':' + parts[1] + ':' + parts[2] + ':' + 'deadbeef'.repeat(8)
    const { data } = await hostClient.rpc('mark_attended_by_token', {
      p_slot_id: slotId,
      p_token:   forgedToken,
    })
    expect(data.error).toBe('invalid_token_signature')
  })

  it('FRAUD: expired token (tampered exp in the past, original sig invalid) is rejected', async () => {
    const parts = junior1Token.split(':')
    // Change exp to Unix epoch 1 (1970-01-01); keep original sig → sig will be wrong,
    // but exp check fires first (exp=1 < now) and returns token_expired
    const expiredToken = parts[0] + ':' + parts[1] + ':1:' + parts[3]
    const { data } = await hostClient.rpc('mark_attended_by_token', {
      p_slot_id: slotId,
      p_token:   expiredToken,
    })
    expect(data.error).toBe('token_expired')
  })

  it('FRAUD: token for a different slot is rejected (slot mismatch)', async () => {
    const parts = junior1Token.split(':')
    const wrongSlot = '11111111-1111-1111-1111-111111111111'
    // Swap slot_id in payload; sig is now wrong too, but slot mismatch fires first
    const mismatchedToken = parts[0] + ':' + wrongSlot + ':' + parts[2] + ':' + parts[3]
    const { data } = await hostClient.rpc('mark_attended_by_token', {
      p_slot_id: slotId,
      p_token:   mismatchedToken,
    })
    // Token slot_id !== p_slot_id
    expect(data.error).toBe('token_slot_mismatch')
  })

  it('host marks junior1 attended with valid token → success', async () => {
    const { data, error } = await hostClient.rpc('mark_attended_by_token', {
      p_slot_id: slotId,
      p_token:   junior1Token,
    })
    expect(error).toBeNull()
    expect(data.status).toBe('attended')
    expect(data.user_id).toBe(junior1Id)

    const { data: enroll } = await adminSb
      .from('enrollments')
      .select('status, attended_at, checked_in_by')
      .eq('slot_id', slotId).eq('user_id', junior1Id).single()
    expect(enroll!.status).toBe('attended')
    expect(enroll!.attended_at).toBeTruthy()
    expect(enroll!.checked_in_by).toBe(hostId)   // scanner identity recorded
  })

  it('FRAUD: token reuse after successful check-in returns token_already_used', async () => {
    const { data } = await hostClient.rpc('mark_attended_by_token', {
      p_slot_id: slotId,
      p_token:   junior1Token,
    })
    expect(data.error).toBe('token_already_used')
  })

  it('co-judge can also mark attendance via token (generates junior2 token)', async () => {
    const { data: tokenData } = await junior2Client.rpc('generate_checkin_token', {
      p_slot_id: slotId,
    })
    expect(tokenData.error).toBeUndefined()

    const { data } = await judgeClient.rpc('mark_attended_by_token', {
      p_slot_id: slotId,
      p_token:   tokenData.token,
    })
    expect(data.status).toBe('attended')
    expect(data.user_id).toBe(junior2Id)

    const { data: enroll } = await adminSb
      .from('enrollments')
      .select('checked_in_by')
      .eq('slot_id', slotId).eq('user_id', junior2Id).single()
    expect(enroll!.checked_in_by).toBe(judgeId)  // judge's identity recorded
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────
// slot2Id + junior3Id/Client are set up in the outer beforeAll so there are no
// nested beforeAll timing issues when the full test suite runs in parallel.
describe('mark_attended_direct — fraud paths', () => {
  it('FRAUD: junior cannot call mark_attended_direct (unauthorized)', async () => {
    const { data } = await junior3Client.rpc('mark_attended_direct', {
      p_slot_id: slot2Id,
      p_user_id: junior3Id,
    })
    expect(data.error).toBe('unauthorized')
  })

  it('FRAUD: outsider cannot call mark_attended_direct (unauthorized)', async () => {
    const { data } = await outsiderClient.rpc('mark_attended_direct', {
      p_slot_id: slot2Id,
      p_user_id: junior3Id,
    })
    expect(data.error).toBe('unauthorized')
  })

  it('host can mark attendance directly for a junior they see in the room', async () => {
    const { data, error } = await hostClient.rpc('mark_attended_direct', {
      p_slot_id: slot2Id,
      p_user_id: junior3Id,
    })
    expect(error).toBeNull()
    expect(data.status).toBe('attended')
    expect(data.user_id).toBe(junior3Id)

    const { data: enroll } = await adminSb
      .from('enrollments')
      .select('status, checked_in_by')
      .eq('slot_id', slot2Id).eq('user_id', junior3Id).single()
    expect(enroll!.status).toBe('attended')
    expect(enroll!.checked_in_by).toBe(hostId)
  })

  it('idempotent: marking already-attended junior returns already_attended', async () => {
    const { data } = await hostClient.rpc('mark_attended_direct', {
      p_slot_id: slot2Id,
      p_user_id: junior3Id,
    })
    expect(data.status).toBe('already_attended')
  })

  it('marking a non-enrolled user returns not_enrolled', async () => {
    const { data } = await hostClient.rpc('mark_attended_direct', {
      p_slot_id: slot2Id,
      p_user_id: '00000000-0000-0000-0000-000000000000',
    })
    expect(data.error).toBe('not_enrolled')
  })
})

// ─────────────────────────────────────────────────────────────────────────────
describe('app_config is unreachable by clients', () => {
  it('junior cannot SELECT from app_config (no RLS policy)', async () => {
    const { data, error } = await junior1Client
      .from('app_config')
      .select('value')
      .eq('key', 'attendance_hmac_key')
    // RLS blocks — returns empty array or error, never the secret
    expect(data?.length ?? 0).toBe(0)
  })

  it('outsider cannot SELECT from app_config', async () => {
    const { data } = await outsiderClient
      .from('app_config')
      .select('value')
    expect(data?.length ?? 0).toBe(0)
  })
})
